IF (WIN32)
  SET  (DEFINITIONS "/DSIMD_NOSTARTOSPL=0")
ELSE (WIN32)
  SET (DEFINITIONS "-DNDEBUG -g -O2 -std=c++11  -pipe -Wall")
ENDIF (WIN32)

# SET (DEFINITIONS "-g  -O2 -pipe -std=c++0x ")
# IF (WIN32)
#         IF(DEBUG)
#                 SET (DEFINITIONS "-DNDEBUG -std=c++0x")
#         ENDIF(DEBUG)
# ELSE (WIN32)
#         IF(DEBUG)
#                 SET (DEFINITIONS "-ansi -g3 -pg -pipe -std=c++0x")
#         ELSE(DEBUG)
#                 IF(PEDANTIC)
#                         SET (DEFINITIONS "-ansi -g -pg -pipe -Wall -Wstrict-null-sentinel -Weffc++ -Wold-style-cast -pedantic -std=c++0x")
#                         SET (DEBUG 1)
#                 ELSE(PEDANTIC)
#                         SET (DEFINITIONS "-DNDEBUG -O5 -pipe -std=c++0x")
#                 ENDIF(PEDANTIC)
#         ENDIF(DEBUG)
# ENDIF (WIN32)