#!/usr/bin/env python

import rospy

def logger():
    rospy.init_node('param_info_node', anonymous = True)
    rate = rospy.Rate(10)

    # Set a parameter value!    
    rospy.set_param('/info_param', 'methylDragon')

    while not rospy.is_shutdown():
        
        # ROS log is usually shown on the Terminal screen
        rospy.loginfo("info_param value: " + str(rospy.get_param('/info_param')))
        rospy.loginfo("To test it out some more, use: rosparam set /info_param <whatever_you_want>\n")
        rate.sleep()
        
if __name__ == '__main__':
    try:
        logger()
    except rospy.ROSInterruptException:
        pass    
